# Generated by Django 6.0 on 2025-12-29 13:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='image')),
                ('Video', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='video')),
                ('Audio', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audio')),
                ('File', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='file')),
            ],
        ),
    ]
