# Generated by Django 6.0 on 2025-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
                ('Details', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
