# Generated by Django 6.0 on 2025-12-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_contact',
            field=models.IntegerField(),
        ),
    ]
