# Generated by Django 6.0 on 2025-12-31 13:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[app.models.Validators_name]),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(validators=[app.models.validators_roll]),
        ),
    ]
