# Generated by Django 6.0 on 2025-12-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Audio', models.FileField(upload_to='audio/')),
                ('Video', models.FileField(upload_to='video/')),
                ('Document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
